### ISSUE TITLE
generated output does not look right

### ISSUE THREAD

**Issue by sildeag** [picnicprojects/gedcom2html#1]
![Screenshot from 2019-12-11 17-08-51](https://user-images.githubusercontent.com/6589674/70671430-3f5d1580-1c39-11ea-9dbc-a82383edc806.png)

compared to yours:
![Screenshot from 2019-12-11 17-12-33](https://user-images.githubusercontent.com/6589674/70671550-a24eac80-1c39-11ea-9f2d-0abca3819049.png)

**Comment by picnicprojects** [comment]
Hi,
You also need fontawsome in the fonts directory

**Comment by sildeag** [comment]
Thanks for the reply.  I had downloaded from [https://fontawesome.com/] however I had used their current "free" version 5.12.  I realized that something was wrong with the fonts and downloaded their old "free" version 4.7 and copied those fonts into the fonts folder and that worked perfectly.
